#
spring:
  profiles:
    active: dev
   #active:test/release
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  servlet:
    context-path: /
